#!/bin/bash

COMPILER="../terffee/terffee"

#============================================================================
# compile all scripts
#============================================================================
echo "viewkit compiling..."
${COMPILER} -c ./src/viewkit -o ./libs/view/viewkit.min.js -c ./src/libs/view -o ./libs/view/mainview.min.js -c ./src/libs/model -o ./libs/model/
${COMPILER} -w -c ./src/viewkit -o ./libs/view/viewkit.min.js -c ./src/libs/view -o ./libs/view/mainview.min.js -c ./src/libs/model -o ./libs/model/
